### ISSUE TITLE
HighSierra

### ISSUE THREAD

**Issue by SwaggyZhang** [IamCarron/Lenovo-Ideapad-700-15isk-Hackintosh-Monterey#2]
Hello, thank you for your valuable work! 
If I choose the 10.13.6 (High Sierra) on the same laptop as yours, can the discrete GPU be available?

**Comment by IamCarron** [comment]
As far i know NVIDIA gpu wont work by default

**Comment by SwaggyZhang** [comment]
>
How about the NVIDIA webdriver?

**Comment by IamCarron** [comment]
I didnt saw anyone traying and succeded so i think it wont work

**Comment by SwaggyZhang** [comment]
> I didnt saw anyone traying and succeded so i think it wont work

Thank you!
