### ISSUE TITLE
Can not find 'Install Mac OS'

### ISSUE THREAD

**Issue by SwaggyZhang** [IamCarron/Lenovo-Ideapad-700-15isk-Hackintosh-Monterey#3]
Thank you for your valuable work!
I copied your EFI folder and prepared the online recovery for Catalina.
However, there is nothing about 'MacOS' in the opencore boot menu.

**Comment by IamCarron** [comment]
You probably need to press space on the boot menu.

**Comment by SwaggyZhang** [comment]
> You probably need to press space on the boot menu.

Hello, I successfully installed Catalina. And my AUX is available.

You can change the 'alcid' to 28 in boot-args to activate your 3.5 mm headphone jack. Thus, the headphone and microphone are both working.

As for the HDMI, I find that the built-in screen will be black if an external monitor is connected to the laptop and the monitor is working.

The built-in screen is only recognized by macOS and lit, but it is still black and does not show anything.

Does the same thing happen to your computer's HDMI output?
